name: Code Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    name: Coverage - ${{ matrix.os }} / Swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - swift: 5.9
            os: ubuntu-22.04
          - swift: 6.0
            os: ubuntu-latest
          - swift: 6.0
            os: macos-latest
          - swift: 5.9
            os: macos-latest  # якщо хочеш тестувати 5.9 і на macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build library
        run: swift build

      - name: Run tests with coverage
        run: swift test --enable-code-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: .build/debug/codecov/*.profdata
          fail_ci_if_error: true
