name: Deploy HealthChecks DocC

on:
  push:
    branches: ["docc"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build HealthChecks DocC 🛠
        run: |
          TMP_DOCS=$(mktemp -d)
          echo "Using temporary docs folder: $TMP_DOCS"

          # 🔹 Збираємо тільки HealthChecks без залежностей
          xcrun docc convert Sources/HealthChecks/HealthChecks.docc \
            --output .build/docs/HealthChecks.doccarchive

          # 🔹 Трансформація для статичного хостингу
          xcrun docc process-archive \
            transform-for-static-hosting \
            .build/docs/HealthChecks.doccarchive \
            --output-path "$TMP_DOCS" \
            --hosting-base-path fs-app-health-checks

          # 🔹 Копіюємо готову документацію в docs
          rm -rf docs
          mkdir -p docs
          cp -R "$TMP_DOCS"/* docs/

          # 🔹 Редірект на index.html
          echo "<script>window.location.href += '/documentation/healthchecks'</script>" > docs/index.html

      - name: Upload artifact 📜
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
