name: Deploy DocC

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: macos-14

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Select Xcode 🧰
        run: sudo xcode-select -s /Applications/Xcode.app

      # (опціонально, але корисно для дебагу)
      - name: Show Schemes 🔍
        run: xcodebuild -list

      - name: Build Documentation 📚
        run: |
          xcodebuild docbuild \
            -scheme fs-app-health-checks \
            -destination 'generic/platform=macOS' \
            OTHER_DOCC_FLAGS='--additional-symbol-graph-dir .build/debug --transform-for-static-hosting --hosting-base-path fs-app-health-checks' \          
            DOCC_OUTPUT_DIR=./docs

      - name: Add Redirect Index 🔗
        run: |
          mkdir -p docs
          echo "<script>window.location.href += '/documentation/healthchecks'</script>" > docs/index.html

      - name: Upload artifact 📜
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages 🐙
        id: deployment
        uses: actions/deploy-pages@v4
